version: '3'

services:
  mongo_app:
    container_name: mongo_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo_db:27017/mongo_rrss
    depends_on:
      - mongo_db
    volumes:
      - .:/app

  mongo_db:
    container_name: mongo_db
    image: mongo:latest
    ports:
      - 27020:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
